export const handleDeEncodeQueries = (string: string | undefined) =>
  string
    ?.trim()
    .replace(/\/_next\/data\/(.*?)(.)\.json/g, "")
    .replace(/\/search/g, "")
    .replace(/%20/g, " ")
    .replace(/%20/g, " ")
    .replace(/%2D/g, "-")
    .replace(/%5F/g, "_")
    .replace(/%3B/g, ";")
    .replace(/%3A/g, ":")
    .replace(/%22/g, '"')
    .replace(/%27/g, "'")
    .replace(/%2C/g, ",")
    .replace(/%21/g, "!")
    .replace(/%40/g, "@")
    .replace(/%2A/g, "*")
    .replace(/%2B/g, "+")
    .replace(/%28/g, "(")
    .replace(/%29/g, ")")
    .replace(/%5B/g, "[")
    .replace(/%5D/g, "]")
    .replace(/%5C/g, "\\")
    .replace(/%25/g, "%")
    .replace(/%2F/g, "/")
    .replace(/%3C/g, "<")
    .replace(/%3E/g, ">")
    .replace(/%E2%82%B9/g, "₹")
    .replace(/\+/g, " ")
    .replace(/\?(.*?)(=|$)/g, "")
    .replace(/&(.*?)(=|$)/g, ", ")
    .replace(/, true/g, "")
    .replace(/, false/g, "")
    .replace(/true/g, "")
    .replace(/false/g, "");
